### PR TITLE
bypass xmlcreation

### PR DESCRIPTION
**Pull request by tboulogne**
Hello, could you valid this pull request please ? The goal is to bypass xml creation with xmltodict (create_xml_from_item_obj) in case XML is already formatted during our own products treatment.

So now accepted formats could be, object, etree element or any other XML :-)

Thanks

### CODE REVIEW

**Comment by chocobn69** [comment]
Hi,

First, thanks for the PR.

Could you add a test, change comments and documentation according to this new behavior ?

**Comment by tboulogne** [comment]
@chocobn69 : i just modify the doctring. I'm not aware about the test, i you could help pleasr or i will see this later.

**Comment by chocobn69** [comment]
Hi

First, you need to use a virtualenv in shiba, with `cd your_projett/shiba && virtualenv . && source bin/activate`

Then `pip install tox` to install tox utility

`tox` command will launch every tests


I you need help with unit testing, you can read those two articles (in french) :

- http://sametmax.com/un-gros-guide-bien-gras-sur-les-tests-unitaires-en-python-partie-1/
- http://sametmax.com/un-gros-guide-bien-gras-sur-les-tests-unitaires-en-python-partie-2/


If you still need help, just ask :-)

**Comment by tboulogne** [comment]
Hello @chocobn69 ,

Thanks, i will study this carefully and make change as soon as i finished current project :-).

**Pull request merged**
